# Logica, Control flow y Filtrar
## Adrián Vázquez 
### 4/11/21
---

> Operadores logicos en arreglos  

In [5]:
import numpy as np 
altura_1 = np.array([34, 23,15,67])
altura_2 = np.array([56,12,44,56])

> Podemos utilizar operadores de comparación en los arreglos

In [7]:
altura_1 >= 34        #Obtenemos que valores cumplen con la condición logica y nos regresa valores boolean

array([ True, False, False,  True])

 > Tambien podemos comparar arreglos entre ellos

In [9]:
altura_1 > altura_2   #Vemos que valores dentro del arreglo altura_1 cumplen esa condición y nos imprime 
                      # boolean

array([False,  True, False,  True])

### Para utilizar operadores condicionales en arreglos utilizamos:
<ul>
    <li> np.logical_and()</li>
     <li> np.logical_or()</li>
     <li> np.logical_not()</li>
</ul>
    

> Queremos ver que valores cumplen con las siguientes condicion  

In [12]:
np.logical_and(altura_1 > 20, altura_1 < 66) #nos regresa los valores que cumplan con las dos condiciones  
                                             #como booleans  

array([ True,  True, False, False])

> Tambien  sirven entre arreglos 
> ver que elementos de los arreglos cumplen cieras condiciones

In [13]:
np.logical_and(altura_1 > 20, altura_2 < 50)  #mandamos a buscar e los dos arreglos los valores que cumplan
                                              #con la condicion´ if. Los dos valores en una posicón tienen 
                                              # que ser correctos para regresar un True 

array([False,  True, False, False])