 # Arreglos. 
 ## Adrián Vázquez  28/03/21

 import numpy as np # importar biblioteca  numpy para manejar arreglos y utilizar funciones sobre estos. 
    

## Comandos e información sobre arreglos. 

In [82]:
 lista = [1, 2, 3, 4, 5] # Aqui declaramos una lista con el nombre lista. 
print(lista)             #imprimimos la lista

    
import numpy as np

[1, 2, 3, 4, 5]


In [10]:
arreglo_lista = np.array(lista) #cambiamos el formato lista a arreglo 

print(arreglo_lista)          #imprimos el arreglo, notamos ligeros cambios como la inexistencia de la coma

[1 2 3 4 5]


In [6]:
# los arreglos, basicamente son matrices y cpn ellos se pueden realizar operaciones 
#Ejemplo: veamos la diferencia entre una suma entre arreglos y una entre listas 

arreglo1 = np.array([1,2,3])
arreglo2 = np.array([4,5,6])
print(arreglo1  + arreglo2) 

lista1 = [1,2,3]
lista2 = [4,5,6]
print(lista1  + lista2)       
#Como se puede ver los arreglos realizan una operacion aritmetica  cada entrada de cada arreglo se suma
#mientras las listas, solo se unen.

[5 7 9]
[1, 2, 3, 4, 5, 6]


In [10]:
#Los arreglos tambien estan indexados como una lista y puedes mandar a llamar una posicion o 
# querer saber la posicion de cierta entrada
meses_arreglos = np.array(['ene', 'feb','mar', 'abr', 'mayo', 'jun'])
print(meses_arreglos[0]) #los arreglos al igual que las listas; inician en posición cero

ene


In [12]:
print(meses_arreglos[0:4]) #como en una lista podemos extraer un intervalo de entradas dentro del arreglo

['ene' 'feb' 'mar' 'abr']


In [14]:
print(meses_arreglos[0:5:2]) #Tambien extraer un intervalo de entradas en un cierto patron

['ene' 'mar' 'mayo']


## Arreglos de 2 dimensiones.


In [15]:
#Para hacer un arreglo de dos dimensiones podemos utilizar dos listas, transformarlas en arreglos e indexarlas

In [22]:
nombres_rock = ['freddy', 'jim', 'kurt', 'mick', 'elvis']
apellidos_rock = ['mercury', 'morrison', 'kuven', 'jagger', 'presley']

rock_arreglos = np.array([nombres_rock , apellidos_rock])
print(rock_arreglos)

[['freddy' 'jim' 'kurt' 'mick' 'elvis']
 ['mercury' 'morrison' 'kuven' 'jagger' 'presley']]


In [24]:
#Para conocer caracteristicas de nuestro arreglo, tenemos metodos como: 
#.shape: dimensón de arreglo
#size : total de elementos dentro del arreglo
print(rock_arreglos.shape)
print(rock_arreglos.size)

(2, 5)
10


#### Funciones dentro de los arreglos 

In [27]:
precios = [221.34, 118.87, 332.56, 232.65]
precios_arreglo = np.array([precios])
print(precios_arreglo)

[[221.34 118.87 332.56 232.65]]


In [44]:
# Para obtener la media de los valores dentro de un arreglo 
print(np.mean(precios_arreglo))

#para obtener la desviacion estandar de los valores dentro de un arreglo
desvi = np.std(precios_arreglo)
print(' la desivacion est. es :  ' + str(desvi)) #Para darle un formato presentable concatenamos y la 
                                                 #variable desvi la transformamos a tipo str para poderla 
                                                 # imprimir en una serie de datos string 

226.355
 la desivacion est. es :  75.65927652971578


In [53]:
#Para crear un arreglo solo con el numero de inicio y final (datos numericos)
meses = np.arange(1,13) #creamos un arreglo con inicio en  1 y final  12
print(meses)

# tambien podemos crear arreglos con patron de cambio
meses_patron = np.arange(1,13,2) #saltos de dos posiciones dentro del arreglo
print(meses_patron)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  3  5  7  9 11]


In [60]:
# Para darle un formato de presentacion a un arreglo de 2n 
dia = ['lun', 'mar', 'mier', 'juev', 'vier', 'sab']   #Declaramos nuestras dos listas 
visitantes = [21, 23, 34, 43, 55, 78]
arreglo_visitas = np.array([dia, visitantes])         #Convertimos a un arreglo
print(arreglo_visitas)                  # Se imprime sin formato

formato_visitas = np.transpose(arreglo_visitas) # la funcion transpose() cambia los renglones y columnas 
                                                #de un arreglo haciendolo mas entendible
print(formato_visitas)


[['lun' 'mar' 'mier' 'juev' 'vier' 'sab']
 ['21' '23' '34' '43' '55' '78']]
[['lun' '21']
 ['mar' '23']
 ['mier' '34']
 ['juev' '43']
 ['vier' '55']
 ['sab' '78']]


In [68]:
 # Tambien podemos buscar un elemento dentro de un arreglo
print(arreglo_visitas[0,3])    #renglon 1 fila 3
print(formato_visitas[4, 1])   #renglon 5 fila 2
print(formato_visitas[1, :])   # tomamos los items del renglon 2 
print(formato_visitas[:, 1])   # tomamos los items dela fila 2 

juev
55
['mar' '23']
['21' '23' '34' '43' '55' '78']


In [73]:
# Indexar arreglos 

arreglo_meses = np.array(['ene', 'feb', 'mar', 'abr', 'may'])
arreglo_indice = np.array([1,3,4])            # seleccionamos los items que queremos
print(arreglo_meses)
nuevo_arreglo = arreglo_meses[arreglo_indice]      # creamos un nuevo arreglo con los items del primero 
print(nuevo_arreglo)                          



['ene' 'feb' 'mar' 'abr' 'may']
['feb' 'abr' 'may']


In [76]:
# Booleanos en arreglos
arreglo2_meses = np.array(['ene', 'feb', 'mar', 'abr', 'may'])
arreglo_boolean = np.array([True, False, True, True, False]) # Seleccionamos los items que queremos 
                                                             # que aparezcan en el nuevo arreglo

print(arreglo2_meses[arreglo_boolean])



['ene' 'mar' 'abr']


In [81]:
# Booleanos: Condicionales dentro de arreglos

ingresos = np.array([241.43, 343.23, 453.21, 231.32 ])
print(ingresos)

condicion_boolean = (ingresos > 242)  #Busca que items dentro del arreglo cumplan la condicion 
                                      # y los traduce a booleanos (True o False)
print(condicion_boolean)

[241.43 343.23 453.21 231.32]
[False  True  True False]
